build:
  maxIssues: 0
  excludeCorrectable: false

config:
  validation: true
  warningsAsErrors: false

complexity:
  LongMethod:
    threshold: 80
  LongParameterList:
    functionThreshold: 10
    constructorThreshold: 10
  TooManyFunctions:
    thresholdInFiles: 30
    thresholdInClasses: 25
    thresholdInObjects: 20
  CyclomaticComplexMethod:
    threshold: 20

style:
  MaxLineLength:
    maxLineLength: 140
  MagicNumber:
    active: false
  ReturnCount:
    max: 4
  UnusedPrivateMember:
    active: true
  WildcardImport:
    active: false

naming:
  FunctionNaming:
    functionPattern: "[a-z][a-zA-Z0-9]*"
    ignoreAnnotated: ["Composable"]
  TopLevelPropertyNaming:
    constantPattern: "[A-Z][A-Za-z0-9]*"

exceptions:
  TooGenericExceptionCaught:
    active: false
  SwallowedException:
    active: false

performance:
  SpreadOperator:
    active: false
